services:
   rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      hostname: rabbitmq
      restart: unless-stopped
      environment:
         - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
         - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      volumes:
         - ${DOCKER_DATA}/rabbitmq:/var/lib/rabbitmq
      ports:
         - '5672:5672'
         - '15672:15672'
      logging:
         driver: 'json-file'
         options:
            max-size: '5m'
            max-file: '10'
      networks:
         - jarvis
