version: "3.7"
# Truncate Log Files: https://tecadmin.net/truncate-docker-container-logfile/
# List log files for all containers
# sudo du -h $(docker inspect --format='{{.LogPath}}' $(docker ps -qa))
services:

### Build

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=buildvm
      - POSTGRES_PASSWORD=$PASSWORD
      - POSTGRES_DB=gitea
    networks:
      - dev-network

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - APP_NAME="Gitea"
      - USER_UID=$PUID
      - USER_GID=$PGID
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__USER=buildvm
      - GITEA__database__PASSWD=$PASSWORD
      - GITEA__database__NAME=gitea
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - dev-network

#  sonarqube:
#    image: sonarqube:latest
#    container_name: sonarqube
#    hostname: sonarqube
#    restart: unless-stopped
#    environment:
#     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
#     - SONARQUBE_JDBC_USERNAME=sonar
#     - SONARQUBE_JDBC_PASSWORD=$PASSWORD
#    ports:
#      - 9000:9000
#    depends_on:
#      - postgres
#    volumes:
#      - ./sonarqube/conf:/opt/sonarqube/conf
#      - ./sonarqube/data:/opt/sonarqube/data
#      - ./sonarqube/logs:/opt/sonarqube/logs
#      - ./sonarqube/extensions:/opt/sonarqube/extensions
#      - ./sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#    networks:
#      - dev-network

### Monitoring / Charts & Graphs

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: root
    ports:
      - 3100:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - dev-network
    depends_on:
      - prometheus

# Prometheu: Create a prometheus.yml config file in ~/.docker/prometheus and copy/paste the following (excluding #)
# scrape_configs:
# - job_name: cadvisor
#   scrape_interval: 5s
#   static_configs:
#   - targets:
#     - cadvisor:3110

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    user: root
    ports:
      - "3101:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
    networks:
     - dev-network
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    ports:
      - 3110:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - dev-network
    depends_on:
      - redis

  structurizr:
    image: structurizr/onpremises
    container_name: structurizr
    hostname: structurizr
    restart: unless-stopped
    ports:
      - 3200:8080
    volumes:
      - ./structurizr:/data
    networks:
      - dev-network

### Artifacts
  # Artifactory comes with a pre-configured default "admin" account. Username: admin, Password: password.
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    hostname: artifactory
    user: root
    restart: unless-stopped
    ports:
      - 8081:8081 # This must not be changed as it is expected by the container
      - 8082:8082 # This must not be changed as it is expected by the container
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
    networks:
      - dev-network

#  registry:
#    image: registry:2
#    container_name: registry
#    hostname: registry
#    restart: unless-stopped
#    environment:
#      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
#    ports:
#      - 5000:5000
#    volumes:
#      - ./registry:/data
#    networks:
#      - dev-network

### Dbs 
  mongodb:
    image: mongo:4.4.7 #mongo:latest
    container_name: "mongodb"
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: $PASSWORD
    ports:
      - "27018:27017"
    networks:
      - dev-network
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/config:/configdb

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: $PASSWORD
    volumes:
      - ./rabbitmq/dataq:/var/lib/rabbitmq
      - ./rabbitmq/config:/etc/rabbitmq
    networks:
      - dev-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - dev-network

### Configs & Secrets

  vault:
    image: vault:latest
    container_name: vault
    hostname: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - 3300:8200
    volumes:
      - ./vault/data:/vault/file
      - ./vault/config:/vault/config
    command: server -dev -dev-root-token-id=root
    networks:
      - dev-network

#  zookeeper:
#    image: zookeeper:latest
#    container_name: zookeeper
#    hostname: zookeeper
#    environment:
#      ZOO_MY_ID: 1
#      ZOO_SERVERS: server.1=zookeeper:2888:3888
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
##     - 3400:8080
#    volumes:
#      - ./zookeeper/data:/data
#      - ./zookeeper/config:/conf
#    networks:
#      - dev-network

# Misc
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    command: --schedule "0 0 4 * * *" --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    networks:
      - dev-network




networks:
   dev-network:
      driver: bridge